alias cdas='cd /data/sfsf/workspace/trunk/au-timemanagement/au-timemanagement-sapui5-web'
alias cda='cd /data/sfsf/workspace/trunk/au-timemanagement'
alias cdbs='cd /data/sfsf/workspace/trunk/build-system'
alias gs='git status'
alias gcm='git checkout master'
alias gc='git checkout'
alias gpm='git checkout master && git pull && git checkout -'
alias cdf='cd $(find / -maxdepth 6 ! -iname ".*" -type d 2> >(grep -v denied >&2) | sort | fzf --header="Change to directory")' 
alias pauseTomcat='docker pause $(docker ps -qa)'
alias unpauseTomcat='docker unpause $(docker ps -qa)'
alias wpods='watch kubectl get pods'
alias cfpod='kubectl get pods | awk '"'"'{print $1}'"'"' | grep mybizx-cf'
alias gwd='gw deploy --rerun-tasks --no-scan'
