
Œ
?grvy:org.codenarc.rule.grails.GrailsServletContextReferenceRuleI
grvy:org.codenarc.rule.grails.GrailsServletContextReferenceRuleMINOR
€
9grvy:org.codenarc.rule.convention.HashtableIsObsoleteRuleC
grvy4org.codenarc.rule.convention.HashtableIsObsoleteRuleMINOR
r
2grvy:org.codenarc.rule.basic.EmptyForStatementRule<
grvy-org.codenarc.rule.basic.EmptyForStatementRuleMINOR
v
4grvy:org.codenarc.rule.exceptions.ThrowThrowableRule>
grvy/org.codenarc.rule.exceptions.ThrowThrowableRuleMAJOR
v
4grvy:org.codenarc.rule.basic.EmptyWhileStatementRule>
grvy/org.codenarc.rule.basic.EmptyWhileStatementRuleMINOR
„
;grvy:org.codenarc.rule.basic.EmptySynchronizedStatementRuleE
grvy6org.codenarc.rule.basic.EmptySynchronizedStatementRuleMINOR
µ
8grvy:org.codenarc.rule.grails.GrailsStatelessServiceRuley
grvy3org.codenarc.rule.grails.GrailsStatelessServiceRuleMAJOR"5
ignoreFieldNames!'dataSource,scope,sessionFactory,
Ž
@grvy:org.codenarc.rule.concurrency.VolatileLongOrDoubleFieldRuleJ
grvy;org.codenarc.rule.concurrency.VolatileLongOrDoubleFieldRuleMAJOR
Š
>grvy:org.codenarc.rule.unused.UnusedPrivateMethodParameterRuleH
grvy9org.codenarc.rule.unused.UnusedPrivateMethodParameterRuleMINOR
j
.grvy:org.codenarc.rule.basic.EmptyTryBlockRule8
grvy)org.codenarc.rule.basic.EmptyTryBlockRuleMINOR
¦
0grvy:org.codenarc.rule.size.NestedBlockDepthRuler
grvy+org.codenarc.rule.size.NestedBlockDepthRuleMAJOR"
maxNestedBlockDepth5"
ignoreRegex.*(b|B)uilder
p
1grvy:org.codenarc.rule.basic.EmptyIfStatementRule;
grvy,org.codenarc.rule.basic.EmptyIfStatementRuleMINOR
n
0grvy:org.codenarc.rule.exceptions.ThrowErrorRule:
grvy+org.codenarc.rule.exceptions.ThrowErrorRuleMAJOR
p
1grvy:org.codenarc.rule.logging.SystemErrPrintRule;
grvy,org.codenarc.rule.logging.SystemErrPrintRuleMAJOR
l
/grvy:org.codenarc.rule.basic.EmptyElseBlockRule9
grvy*org.codenarc.rule.basic.EmptyElseBlockRuleMINOR
€
9grvy:org.codenarc.rule.basic.EmptyInstanceInitializerRuleC
grvy4org.codenarc.rule.basic.EmptyInstanceInitializerRuleMINOR
v
4grvy:org.codenarc.rule.exceptions.ThrowExceptionRule>
grvy/org.codenarc.rule.exceptions.ThrowExceptionRuleMAJOR
„
;grvy:org.codenarc.rule.exceptions.ThrowRuntimeExceptionRuleE
grvy6org.codenarc.rule.exceptions.ThrowRuntimeExceptionRuleMAJOR
d
+grvy:org.codenarc.rule.basic.EmptyClassRule5
grvy&org.codenarc.rule.basic.EmptyClassRuleMINOR
p
1grvy:org.codenarc.rule.basic.EqualsOverloadedRule;
grvy,org.codenarc.rule.basic.EqualsOverloadedRuleMINOR
|
7grvy:org.codenarc.rule.basic.DuplicateCaseStatementRuleA
grvy2org.codenarc.rule.basic.DuplicateCaseStatementRuleMINOR
~
8grvy:org.codenarc.rule.imports.ImportFromSunPackagesRuleB
grvy3org.codenarc.rule.imports.ImportFromSunPackagesRuleMINOR
‰
<grvy:org.codenarc.rule.concurrency.NestedSynchronizationRuleI
grvy7org.codenarc.rule.concurrency.NestedSynchronizationRuleCRITICAL
¼
7grvy:org.codenarc.rule.unused.UnusedMethodParameterRule€
grvy2org.codenarc.rule.unused.UnusedMethodParameterRuleMINOR"
ignoreClassRegex
.*Category"
ignoreRegexignore|ignored

0grvy:org.codenarc.rule.basic.EmptyCatchBlockRuleY
grvy+org.codenarc.rule.basic.EmptyCatchBlockRuleMINOR"
ignoreRegexignore|ignored
b
*grvy:org.codenarc.rule.logging.PrintlnRule4
grvy%org.codenarc.rule.logging.PrintlnRuleMINOR
v
4grvy:org.codenarc.rule.exceptions.CatchExceptionRule>
grvy/org.codenarc.rule.exceptions.CatchExceptionRuleMAJOR
Ž
@grvy:org.codenarc.rule.concurrency.SystemRunFinalizersOnExitRuleJ
grvy;org.codenarc.rule.concurrency.SystemRunFinalizersOnExitRuleMAJOR
€
9grvy:org.codenarc.rule.concurrency.SynchronizedMethodRuleC
grvy4org.codenarc.rule.concurrency.SynchronizedMethodRuleMAJOR
|
7grvy:org.codenarc.rule.design.CloneableWithoutCloneRuleA
grvy2org.codenarc.rule.design.CloneableWithoutCloneRuleMINOR
u
2grvy:org.codenarc.rule.concurrency.ThreadYieldRule?
grvy-org.codenarc.rule.concurrency.ThreadYieldRuleCRITICAL
o
1grvy:org.codenarc.rule.logging.SystemOutPrintRule:
grvy,org.codenarc.rule.logging.SystemOutPrintRuleINFO
r
2grvy:org.codenarc.rule.basic.EqualsAndHashCodeRule<
grvy-org.codenarc.rule.basic.EqualsAndHashCodeRuleMINOR
‡
;grvy:org.codenarc.rule.exceptions.CatchRuntimeExceptionRuleH
grvy6org.codenarc.rule.exceptions.CatchRuntimeExceptionRuleCRITICAL
–
Dgrvy:org.codenarc.rule.grails.GrailsPublicControllerMethodRule.fixedN
grvy?org.codenarc.rule.grails.GrailsPublicControllerMethodRule.fixedMINOR
z
6grvy:org.codenarc.rule.convention.VectorIsObsoleteRule@
grvy1org.codenarc.rule.convention.VectorIsObsoleteRuleMINOR
Œ
?grvy:org.codenarc.rule.exceptions.ThrowNullPointerExceptionRuleI
grvy:org.codenarc.rule.exceptions.ThrowNullPointerExceptionRuleMAJOR
n
0grvy:org.codenarc.rule.exceptions.CatchErrorRule:
grvy+org.codenarc.rule.exceptions.CatchErrorRuleMAJOR
r
2grvy:org.codenarc.rule.basic.EmptyFinallyBlockRule<
grvy-org.codenarc.rule.basic.EmptyFinallyBlockRuleMINOR
~
8grvy:org.codenarc.rule.basic.AssignmentInConditionalRuleB
grvy3org.codenarc.rule.basic.AssignmentInConditionalRuleMAJOR
|
7grvy:org.codenarc.rule.basic.ReturnFromFinallyBlockRuleA
grvy2org.codenarc.rule.basic.ReturnFromFinallyBlockRuleMAJOR
Œ
?grvy:org.codenarc.rule.basic.ThrowExceptionFromFinallyBlockRuleI
grvy:org.codenarc.rule.basic.ThrowExceptionFromFinallyBlockRuleMAJOR
r
2grvy:org.codenarc.rule.logging.PrintStackTraceRule<
grvy-org.codenarc.rule.logging.PrintStackTraceRuleMAJOR
œ
4grvy:org.codenarc.rule.unused.UnusedPrivateFieldRuled
grvy/org.codenarc.rule.unused.UnusedPrivateFieldRuleMAJOR"$
ignoreFieldNamesserialVersionUID
’
1grvy:org.codenarc.rule.braces.ElseBlockBracesRule]
grvy,org.codenarc.rule.braces.ElseBlockBracesRuleMINOR" 
bracesRequiredForElseIffalse

?grvy:org.codenarc.rule.exceptions.CatchNullPointerExceptionRuleL
grvy:org.codenarc.rule.exceptions.CatchNullPointerExceptionRuleCRITICAL
€
9grvy:org.codenarc.rule.naming.ClassNameSameAsFilenameRuleC
grvy4org.codenarc.rule.naming.ClassNameSameAsFilenameRuleMINOR
x
5grvy:org.codenarc.rule.unused.UnusedPrivateMethodRule?
grvy0org.codenarc.rule.unused.UnusedPrivateMethodRuleMAJOR
|
7grvy:org.codenarc.rule.basic.EmptyStaticInitializerRuleA
grvy2org.codenarc.rule.basic.EmptyStaticInitializerRuleMINOR
f
,grvy:org.codenarc.rule.basic.EmptyMethodRule6
grvy'org.codenarc.rule.basic.EmptyMethodRuleMINOR
x
5grvy:org.codenarc.rule.basic.EmptySwitchStatementRule?
grvy0org.codenarc.rule.basic.EmptySwitchStatementRuleMINOR
z
6grvy:org.codenarc.rule.unused.UnusedVariableRule.fixed@
grvy1org.codenarc.rule.unused.UnusedVariableRule.fixedMAJOR
l
/grvy:org.codenarc.rule.imports.UnusedImportRule9
grvy*org.codenarc.rule.imports.UnusedImportRuleMAJOR
v
4grvy:org.codenarc.rule.convention.InvertedIfElseRule>
grvy/org.codenarc.rule.convention.InvertedIfElseRuleMAJOR
r
2grvy:org.codenarc.rule.imports.DuplicateImportRule<
grvy-org.codenarc.rule.imports.DuplicateImportRuleMAJOR
~
8grvy:org.codenarc.rule.imports.ImportFromSamePackageRuleB
grvy3org.codenarc.rule.imports.ImportFromSamePackageRuleMAJOR
z
6grvy:org.codenarc.rule.convention.ConfusingTernaryRule@
grvy1org.codenarc.rule.convention.ConfusingTernaryRuleMAJOR
‚
:grvy:org.codenarc.rule.imports.UnnecessaryGroovyImportRuleD
grvy5org.codenarc.rule.imports.UnnecessaryGroovyImportRuleMAJOR